Updated the cd pipeline

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -38,8 +38,16 @@ jobs:
             sudo usermod -aG docker $USER
           fi
 
+          # Login to DockerHub on EC2
+          echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
+          
           sudo docker pull mohamadtr/streamlit-app:tagname
-          sudo fuser -k 80/tcp || true
+
+          # Stop any running containers
+          sudo docker stop $(sudo docker ps -a -q) || true
+
+          # Remove stopped containers (optional cleanup)
+          sudo docker rm $(sudo docker ps -a -q) || true
 
           sudo docker run -d -p 80:80 mohamadtr/streamlit-app:tagname
           EOF 
