Fixed the cd workflow to include the installation on Docker

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -31,7 +31,15 @@ jobs:
       - name: Deploy Docker image to EC2
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
-          sudo yum install docker -y
+
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found, installing Docker..."
+            sudo apt-get update
+            sudo apt-get install docker.io -y
+            sudo systemctl start docker
+          fi
+
           docker pull mohamadtr/streamlit-app:tagname
           docker stop $(docker ps -a -q) || true
           docker run -d -p 80:80 mohamadtr/streamlit-app:tagname
